### ISSUE TITLE
Counts and totals

### ISSUE THREAD

**Issue by Nightblade** [caxerx/PoEHarvestPlanner#5]
Would be nice to see counts and totals, something like this:

Type  | Wild | Vivid | Primal | Total # | Life Force
------ | ----- | ------ | ------- | -------- | ---------
Pylon | 10    | 10    | 10       | 30       | 300
Storage | etc
Dispenser | etc

**Comment by caxerx** [comment]
Sure, will add to the planned feature!

**Comment by caxerx** [comment]
Implemented and deployed on #8 , Enjoy :)
